/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_model_classes_MsgMod */

#ifndef _Included_com_model_classes_MsgMod
#define _Included_com_model_classes_MsgMod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_model_classes_MsgMod
 * Method:    sendMsg
 * Signature: (Lcom/model/classes/SendMsgReqData;Lcom/model/classes/ImSendMsgCallbackFunc;)I
 */
JNIEXPORT jint JNICALL Java_com_example_myjni_classes_MsgMod_sendMsg
  (JNIEnv *, jobject, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
