/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jniclass_MsgMod */

#ifndef _Included_com_jniclass_MsgMod
#define _Included_com_jniclass_MsgMod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jniclass_MsgMod
 * Method:    sendMsg
 * Signature: (Lcom/jniclass/SendMsgReqData;Lcom/jniclass/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_jniclass_MsgMod_sendMsg
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
